Ensure the metrics path can be customized.
ttys3/axum-otel-metrics pull request #72
Opened 2023-09-19 14:46 UTC by DFINITYManu

With this, users gain the ability to customize the URL path at which metrics are served.

2023-09-21 01:33 UTC, ttys3 commented on src/lib.rs
> +    /// Create a Router that has a customized listen metrics path
that will works.

but I think it should implemented in the builder. 

and we just need to add a metrics_path field to the state.

then, the router builder can get it

2023-09-27 12:07 UTC, DFINITYManu commented on src/lib.rs
> +    pub fn path_route<S>(&self, path: String) -> Router<S> {
Done.

2023-10-03 10:01 UTC, DFINITYManu commented
How's it looking like now?

2023-10-09 12:44 UTC, ttys3 requested changes

2023-10-09 12:44 UTC, ttys3 commented on src/lib.rs
> +        v.path = "/metrics".to_string();
this can be something like:

```rust
    MyConfiguration {
        check: true,
        ..Default::default()
    };
```

2023-10-24 14:16 UTC, ttys3 requested changes

2023-10-24 14:16 UTC, ttys3 commented on src/lib.rs
> +        HttpMetricsLayerBuilder::new()
sorry for the delay, been busy

2023-10-26 18:30 UTC, merged